In [27]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score


# Read data from CSV file
df = pd.read_csv('output1.csv')

# Extract features (vata, pitta, kapha) and labels (Prakriti) from the DataFrame
scores = np.array(df[['Q1', 'Q2', 'Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15','Q16','Q17','Q18','Q19','Q20','Q21','Q22','Q23','Q24','Q25','Q26','Q27','Q28','Q29','Q30']])
labels = np.array(df['RESULT'])
d={0:'vata',1:'pitta',2:'kappa',3:'vata-pitta',4:"vata-kapha",5:'pitta-kapha',6:'vata-pitta-kapha'}
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(scores, labels, test_size=0.2)
# Create a RandomForestClassifier with 500 estimators
clf = RandomForestClassifier(n_estimators=100)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions for the test set
y_pred = clf.predict(X_test)

# Generate and print the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Make a prediction for a new data point ([15, 7, 8])

new_prediction = clf.predict(np.array(np.array([[1,0,2,1,2,1,2,0,2,0,1,1,2,1,2,0,0,2,1,1,2,1,2,0,2,0,1,2,1,0]])))
print("New Prediction:", d[new_prediction[0]])


Confusion Matrix:
[[47  6  5  0  0]
 [ 4 66  9  0  0]
 [10  7 43  0  0]
 [ 2  0  0  0  0]
 [ 0  0  1  0  0]]
Accuracy: 0.78
New Prediction: pitta


In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Read data from CSV file
df = pd.read_csv('output1.csv')

# Extract scores (vata, pitta, kapha) and labels variable for regression
scores = np.array(df[['Q1', 'Q2', 'Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15','Q16','Q17','Q18','Q19','Q20','Q21','Q22','Q23','Q24','Q25','Q26','Q27','Q28','Q29','Q30']])
labels = np.array(df['RESULT'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(scores, labels, test_size=0.2)

# Create a LinearRegression model
regressor = LinearRegression()

# Train the model on the training data
regressor.fit(X_train, y_train)

# Make predictions for the test set
y_pred = regressor.predict(X_test)

# Evaluate the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Make a prediction for a new data point ([1,0,2,1,2,1,2,0,2,0,1,1,2,1,2,0,0,2,1,1,2,1,2,0,2,0,1,2,1,0])
new_prediction = int(round(regressor.predict(np.array([[1,0,2,1,2,1,2,0,2,0,1,1,2,1,2,0,0,2,1,1,2,1,2,0,2,0,1,2,1,0]]))[0]))
print("New Prediction:", d[new_prediction])


Mean Squared Error: 0.32508558908813745
New Prediction: pitta


In [21]:
import joblib
joblib.dump(clf, 'model.joblib')

['model.joblib']